
# Aufruf:   docker compose up
#           docker compose down
#           docker compose exec filiale bash

---
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:
  filiale:
    #image: juergenzimmermann/filiale:1.0.0-dockerfile
    image: juergenzimmermann/filiale:1.0.0
    ports:
      - published: 8080
        target: 8080
    #working_dir: /application
    volumes:
      - type: bind
        source: C:\Zimmermann\volumes\filiale-v1
        target: /tmp
    environment:
      TZ: Europe/Berlin
      SPRING_PROFILES_ACTIVE: dev
      SERVER_TOMCAT_BASEDIR: /tmp
      REQUEST_RESPONSE_LOGLEVEL: debug
      APPLICATION_LOGLEVEL: trace
      JAVA_OPTS: "--enable-preview"
    container_name: filiale
    hostname: filiale
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
