# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#                                       $env:TAG = '1.0.0'
#           skaffold dev
#           skaffold delete
# https://skaffold.dev/docs/references/yaml
# https://skaffold-latest.firebaseapp.com/docs/references/yaml
# https://github.com/GoogleContainerTools/skaffold/tree/master/docs/content/en/schemas
apiVersion: skaffold/v3
kind: Config
metadata:
  name: filiale
# https://skaffold.dev/docs/pipeline-stages/builders
build:
  artifacts:
    - image: juergenzimmermann/filiale
      # https://skaffold.dev/docs/pipeline-stages/builders/buildpacks
      # https://paketo.io/docs/howto/java
      # https://www.youtube.com/watch?v=aI19ZYV4-7o
      buildpacks:
        builder: paketobuildpacks/builder:base
        env: [BP_JVM_VERSION=19.0.0]
        #env: [BP_JVM_VERSION=19.*]
        dependencies:
          paths: [src, build.gradle.kts]
  # https://skaffold.dev/docs/pipeline-stages/taggers
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
deploy:
  # https://skaffold.dev/docs/pipeline-stages/deployers/helm
  # Alternativen: Kustomize, kpt, kubectl
  helm:
    releases:
      - name: filiale
        chartPath: extras/filiale
        valuesFiles: [extras/filiale/values.yaml]
        namespace: acme
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: filiale
            chartPath: extras/filiale
            valuesFiles: [extras/filiale/values.yaml, extras/filiale/dev.yaml]
            namespace: acme
    # https://skaffold.dev/docs/pipeline-stages/port-forwarding
    portForward:
      - resourceType: service
        resourceName: filiale
        port: http-svc
