# Aufruf:   docker compose up
#           docker compose down

# Netzwerk "postgres_default" für die die Container durch den Verzeichnisnamen
# BEACHTE: Bei "pgadmin" immer Ausloggen. Sonst: Fehlermeldung "The CSRF session token is missing."

# docker compose exec postgres bash
#   psql --username=postgres
#   cat /usr/share/postgresql/postgresql.conf.sample > /var/lib/postgresql/data/my-postgresql.conf
# docker compose exec pgadmin ash

---
services:
  postgres_container:
    image: postgres:15.1-bullseye
    ports:
      - published: 5432
        target: 5432
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/postgres/data
        target: /var/lib/postgresql/data
      - type: bind
        source: C:/Zimmermann/volumes/postgres/postgresql.conf
        target: /etc/postgresql/postgresql.conf
        read_only: true
      - type: bind
        source: C:/Zimmermann/volumes/postgres/tablespace
        target: /var/lib/postgresql/tablespace
      - type: bind
        source: C:/Zimmermann/volumes/postgres/sql
        target: /sql
        read_only: true
    env_file: [postgres.env]
    # beim 1. Start *NICHT* den eingeschraenkten Linux-User "postgres" verwenden, d.h. implizit "root"
    user: "postgres:postgres"
    # docker inspect postgres --format '{{ .Id }}: SecurityOpt={{ .HostConfig.SecurityOpt }}'
    security_opt:
      - label:user:postgres
      - no-new-privileges:true
    container_name: postgres_container
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 448M
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname", "postgres", "--username", "postgres"]
      interval: 5s
      timeout: 2s
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - published: 8008
        target: 80
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/postgres/pgadmin
        target: /var/lib/pgadmin
      - type: bind
        source: C:/Zimmermann/volumes/postgres/pgadmin4
        target: /var/lib/pgadmin4
    env_file: [pgadmin.env]
    user: "pgadmin:5050"
    container_name: pgadmin
    hostname: pgadmin
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 448M
  filiale:
    image: juergenzimmermann/filiale
    ports:
      - published: 8080
        target: 8080
    volumes:
      - type: bind
        source: C:\Zimmermann\volumes\filiale-v1
        target: /tmp
    environment:
      TZ: Europe/Berlin
      SPRING_PROFILES_ACTIVE: dev
      SERVER_TOMCAT_BASEDIR: /tmp
      REQUEST_RESPONSE_LOGLEVEL: debug
      APPLICATION_LOGLEVEL: trace
      JAVA_OPTS: "--enable-preview"
    container_name: filiale
    hostname: filiale
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

