### Einen neuen Kunden anlegen
GRAPHQL {{baseUrl}}/graphql

mutation {
  create(
    input: {
      name: "Graphql"
      email: "graphql@graphql.de"
      homepage: "https://graphql.de"
      umsatz: {
        betrag: "200"
        waehrung: "EUR"
      }
      adresse: {
        plz: "99999"
        ort: "Graphqlort"
      }
    }
  ) {
    id
  }
}

### Einen neuen Kunden mit fehlerhaften Daten anlegen
GRAPHQL {{baseUrl}}/graphql

mutation {
  create(
    input: {
      name: "?!:"
      email: "email@"
      homepage: "https://graphql.de"
      umsatz: {
        betrag: "1"
        waehrung: "EUR"
      }
      adresse: {
        plz: "1234"
        ort: ""
      }
    }
  ) {
    id
  }
}
