### Suche mit vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query getFiliale{
  filiale(id: "00000000-0000-0000-0000-000000000001") {
    name
  }
}

### Suche mit nicht-vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query getFiliale{
  filiale(id: "ffffffff-ffff-ffff-ffff-ffffffffffff") {
    name
  }
}

### Suche mit vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filiale(id: "00000000-0000-0000-0000-000000000001") {
    name
    email
    homepage
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}

### Suche alle Kunden als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filialen {
    id
    name
    homepage
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}

### Suche Kunde mit der Emailadresse als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filialen(input: {email: "admin@acme.com"}) {
    id
    name
    homepage
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}

### Suche Kunde mit nicht-vorhandener Emailadresse als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filialen(input: {email: "nicht.vorhanden@acme.com"}) {
    id
  }
}

### Suche Kunden mit dem Nachnamen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filialen(input: {name: "a"}) {
    id
    name
    email
    homepage
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}
### Suche Kunden mit nicht-vorhandenem Nachnamen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  filialen(input: {name: "Nichtvorhanden"}) {
    id
  }
}
