
# https://kubernetes.io/docs/concepts/services-networking/network-policies
# https://hub.armosec.io/docs/c-0054
# https://hub.armosec.io/docs/c-0049

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "filiale.fullname" . }}
  namespace: acme
spec:
  # Spezifikation, auf welche Pods die NetworkPolicy angewendet wird
  podSelector:
    matchLabels:
      {{- include "filiale.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
