
@startuml Filiale

skinparam classAttributeIconSize 0
' skinparam monochrome true

package java {
    package util {
        class UUID
        interface List<T>
        class URL
        class Currency
    }

    package math {
        class BigDecimal
    }

    BigDecimal .up[hidden].> UUID
}

package com.acme.filiale #DDDDDD {
    class Umsatz {
        betrag: BigDecimal
        waehrung: Currency
    }

    class Adresse {
        plz: String
        ort: String
    }

    class Filiale << entity >> {
        id : UUID
        name : String
        email : String
        homepage: URL
        umsatz: Umsatz
    }

    Filiale *--> "0..1" Umsatz : umsatz
    Filiale *--> "1" Adresse : adresse

    Filiale ..> UUID
    Filiale ..> List
    Filiale ..> URL

    Umsatz ..> Currency
    Umsatz ..> BigDecimal
}

hide empty members

footer (c) Tobias Bück

@enduml
